const adminRoutes = {
    base: '/admin',
    pageError: '/page-error',
    dashboard: '/',
    dashboardFilters: '/filter-data',
    customers: '/users',
    updateStatus: '/update-status',
    addUser: '/add-user',
    deleteUser: '/deleteUser/:id',
    editUser: '/editUser',
    // category
    categories: '/categories',
    addCategory: '/addCategory',
    editCategory: '/editCategory',
    softDelete: '/soft-delete/:id',
    restoreCategory: '/restoreCategory/:id',
    deleteCategory: '/deleteCategory/:id',
    // product
    products: '/products',
    addProduct: '/addProduct',
    addProductPost: '/add-product',
    editProduct: '/editProduct',
    editProductPost: '/edit-product/:id',
    softDeleteProduct: '/soft-deleteProduct/:id',
    restoreProduct: '/restoreProduct/:id',
    deleteProduct: '/deleteProduct/:id',
    // order
    orders: '/orders',
    updateOrderStatus: '/update-order-status/:orderId/:productId',
    approveReturn: '/approve-return/:orderId/:productId',
    rejectReturn: '/reject-return/:orderId/:productId',
    // sales
    salesReport: '/sales-report',
    allSales: '/all-sales',
    // coupon
    coupon: '/coupon-page',
    createCoupon: '/create-coupon',
    editCoupon: '/edit-coupon',
    deleteCoupon: '/delete-coupon',
    // offer
    offerManagement: '/offer-management',
    createOffer: '/create-offer',
    editOffer: '/edit-offer/:id',
    deleteOffer: '/delete-offer',
    addOfferProduct: '/add-offer-product',
    applyOfferProduct: '/apply-offer-product',
    removeOfferProduct: '/remove-offer-product',
    addOfferCategory: '/add-offer-category',
    applyOfferCategory: '/apply-offer-category',
    removeOfferCategory: '/remove-offer-category',
    // banner
    bannerPage: '/banners',
    addBanner: '/addBanner',
    deleteBanner: '/delete-banner',
};

module.exports = adminRoutes;
